-- MySQL Script generated by MySQL Workbench
-- Tue Apr 27 10:32:19 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema veiculos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema veiculos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `veiculos` DEFAULT CHARACTER SET latin1 ;
USE `veiculos` ;

-- -----------------------------------------------------
-- Table `veiculos`.`marcas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veiculos`.`marcas` ;

CREATE TABLE IF NOT EXISTS `veiculos`.`marcas` (
  `idmarca` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmarca`),
  UNIQUE INDEX `ix_descricao` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veiculos`.`modelos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veiculos`.`modelos` ;

CREATE TABLE IF NOT EXISTS `veiculos`.`modelos` (
  `idmodelo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `idmarca` INT NOT NULL,
  PRIMARY KEY (`idmodelo`),
  UNIQUE INDEX `ix_descricao` (`nome` ASC),
  INDEX `fk_marca` (`idmarca` ASC),
  CONSTRAINT `fk_marca`
    FOREIGN KEY (`idmarca`)
    REFERENCES `veiculos`.`marcas` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veiculos`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veiculos`.`categorias` ;

CREATE TABLE IF NOT EXISTS `veiculos`.`categorias` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`),
  UNIQUE INDEX `ix_descricao` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veiculos`.`cores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veiculos`.`cores` ;

CREATE TABLE IF NOT EXISTS `veiculos`.`cores` (
  `idcor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcor`),
  UNIQUE INDEX `ix_descricao` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veiculos`.`estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veiculos`.`estados` ;

CREATE TABLE IF NOT EXISTS `veiculos`.`estados` (
  `idestado` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(40) NOT NULL,
  `sigla` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idestado`),
  UNIQUE INDEX `IX_estado` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veiculos`.`cidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veiculos`.`cidades` ;

CREATE TABLE IF NOT EXISTS `veiculos`.`cidades` (
  `idcidade` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `idestado` INT NOT NULL,
  PRIMARY KEY (`idcidade`),
  INDEX `IX_cidade` (`nome` ASC),
  INDEX `FK_cidade` (`idestado` ASC),
  CONSTRAINT `FK_cidade`
    FOREIGN KEY (`idestado`)
    REFERENCES `veiculos`.`estados` (`idestado`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veiculos`.`proprietarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veiculos`.`proprietarios` ;

CREATE TABLE IF NOT EXISTS `veiculos`.`proprietarios` (
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `endereco` VARCHAR(50) NOT NULL,
  `idcidade` INT NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `datanascimento` DATETIME NOT NULL,
  PRIMARY KEY (`cpf`),
  INDEX `FK_Proprietario` (`idcidade` ASC),
  CONSTRAINT `FK_Proprietario`
    FOREIGN KEY (`idcidade`)
    REFERENCES `veiculos`.`cidades` (`idcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veiculos`.`veiculos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veiculos`.`veiculos` ;

CREATE TABLE IF NOT EXISTS `veiculos`.`veiculos` (
  `renavam` INT NOT NULL,
  `chassi` VARCHAR(20) NOT NULL,
  `placa` VARCHAR(20) NOT NULL,
  `idcor` INT NOT NULL,
  `idmodelo` INT NOT NULL,
  `anofabricacao` INT(4) NOT NULL,
  `anomodelo` INT(4) NOT NULL,
  `idcategoria` INT NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`renavam`),
  UNIQUE INDEX `ix_chassi` (`chassi` ASC),
  UNIQUE INDEX `ix_placa` (`placa` ASC),
  INDEX `fk_modelo_veiculo` (`idmodelo` ASC),
  INDEX `fk_categoria_veiculo` (`idcategoria` ASC),
  INDEX `fk_cor_veiculo` (`idcor` ASC),
  INDEX `fk_proprietario_veiculo` (`cpf` ASC),
  CONSTRAINT `fk_modelo_veiculo`
    FOREIGN KEY (`idmodelo`)
    REFERENCES `veiculos`.`modelos` (`idmodelo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_categoria_veiculo`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `veiculos`.`categorias` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cor_veiculo`
    FOREIGN KEY (`idcor`)
    REFERENCES `veiculos`.`cores` (`idcor`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_proprietario_veiculo`
    FOREIGN KEY (`cpf`)
    REFERENCES `veiculos`.`proprietarios` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veiculos`.`combustiveis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veiculos`.`combustiveis` ;

CREATE TABLE IF NOT EXISTS `veiculos`.`combustiveis` (
  `idcombustivel` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idcombustivel`),
  UNIQUE INDEX `ix_descricao` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veiculos`.`tiposinfracoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veiculos`.`tiposinfracoes` ;

CREATE TABLE IF NOT EXISTS `veiculos`.`tiposinfracoes` (
  `idtipoinfracao` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(5,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idtipoinfracao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veiculos`.`agentes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veiculos`.`agentes` ;

CREATE TABLE IF NOT EXISTS `veiculos`.`agentes` (
  `idagente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `datacontratacao` DATE NOT NULL,
  PRIMARY KEY (`idagente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veiculos`.`infracoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veiculos`.`infracoes` ;

CREATE TABLE IF NOT EXISTS `veiculos`.`infracoes` (
  `idinfracao` INT NOT NULL AUTO_INCREMENT,
  `renavam` INT NOT NULL,
  `datahora` DATETIME NOT NULL,
  `local` VARCHAR(50) NOT NULL,
  `idtipoinfracao` INT NOT NULL,
  `velocidade` INT NULL,
  `idagente` INT NULL,
  `observacao` VARCHAR(255) NULL,
  PRIMARY KEY (`idinfracao`),
  INDEX `fk_veiculo` (`renavam` ASC),
  INDEX `fk_tipoinfracao` (`idtipoinfracao` ASC),
  INDEX `fk_agentetransito` (`idagente` ASC),
  CONSTRAINT `fk_veiculo`
    FOREIGN KEY (`renavam`)
    REFERENCES `veiculos`.`veiculos` (`renavam`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tipoinfracao`
    FOREIGN KEY (`idtipoinfracao`)
    REFERENCES `veiculos`.`tiposinfracoes` (`idtipoinfracao`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_agentetransito`
    FOREIGN KEY (`idagente`)
    REFERENCES `veiculos`.`agentes` (`idagente`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veiculos`.`telefones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veiculos`.`telefones` ;

CREATE TABLE IF NOT EXISTS `veiculos`.`telefones` (
  `idtelefone` INT NOT NULL AUTO_INCREMENT,
  `ddd` VARCHAR(2) NOT NULL,
  `numero` VARCHAR(8) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idtelefone`),
  INDEX `fk_telefone_proprietario1` (`cpf` ASC),
  CONSTRAINT `fk_telefone_proprietario1`
    FOREIGN KEY (`cpf`)
    REFERENCES `veiculos`.`proprietarios` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veiculos`.`veiculos_has_combustiveis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veiculos`.`veiculos_has_combustiveis` ;

CREATE TABLE IF NOT EXISTS `veiculos`.`veiculos_has_combustiveis` (
  `renavam` INT NOT NULL,
  `idcombustivel` INT NOT NULL,
  PRIMARY KEY (`renavam`, `idcombustivel`),
  INDEX `fk_veiculos_has_combustiveis_veiculos1` (`renavam` ASC),
  INDEX `fk_veiculos_has_combustiveis_combustiveis1` (`idcombustivel` ASC),
  CONSTRAINT `fk_veiculos_has_combustiveis_veiculos1`
    FOREIGN KEY (`renavam`)
    REFERENCES `veiculos`.`veiculos` (`renavam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_veiculos_has_combustiveis_combustiveis1`
    FOREIGN KEY (`idcombustivel`)
    REFERENCES `veiculos`.`combustiveis` (`idcombustivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
